# Generated by Django 3.0.5 on 2020-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was last modified.')),
                ('animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], help_text='This is the animal to which this breed belongs.', max_length=32)),
                ('name', models.CharField(blank=True, help_text='This field is the name of the race.', max_length=32, null=True)),
                ('description', models.TextField(blank=True, help_text='This is a description of the race.', null=True)),
                ('photo', models.ImageField(blank=True, help_text='This image will be used as visual help.', null=True, upload_to='posts/breeds/photos/')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.UniqueConstraint(fields=('animal', 'name'), name='unique_animal_name'),
        ),
    ]
